apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastfood.fullname" . }}-kitchen-service
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kitchen.service.type }}
  selector:
    app.kubernetes.io/component: kitchen
  {{- include "fastfood.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.kitchen.service.protocol }}
      port: {{ .Values.kitchen.service.port }}
      targetPort: {{ .Values.kitchen.port }}