apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastfood.fullname" . }}-monolith
  labels:
    app.kubernetes.io/component: monolith
  {{- include "fastfood.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: monolith
    {{- include "fastfood.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: monolith
      {{- include "fastfood.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              key: app.host
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: app.port
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: app.jwt_secret
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: db.host
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: db.port
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: db.username
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: db.password
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: db.database
              name: {{ include "fastfood.fullname" . }}-monolith-config
        image: {{ .Values.monolith.image }}:{{ .Values.monolith.tag }}
        name: {{ include "fastfood.fullname" . }}-monolith
        ports:
        - containerPort: {{ .Values.monolith.port }}
        resources:
          limits:
            cpu: {{ .Values.monolith.resources.cpu.limits | quote }}
            memory: {{ .Values.monolith.resources.memory.limits | quote }}
          requests:
            cpu: {{ .Values.monolith.resources.cpu.requests | quote }}
            memory: {{ .Values.monolith.resources.memory.requests | quote }}
      initContainers:
      - command:
        - sh
        - -c
        - {{ .Values.monolith.migrationCommand | quote }}
        image: {{ .Values.monolith.image }}:{{ .Values.monolith.tag }}
        name: migrations
        env:
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: db.host
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: db.port
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: db.username
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: db.password
              name: {{ include "fastfood.fullname" . }}-monolith-config
        - name: MYSQL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: db.database
              name: {{ include "fastfood.fullname" . }}-monolith-config

