apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastfood.fullname" . }}-monolith-config
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
data:
  app.host: {{ .Values.monolith.host | quote }}
  app.port: {{ .Values.monolith.port | quote }}
  app.jwt_secret: {{ .Values.monolith.jwt.secret | quote }}
  db.host: {{ .Values.monolith.db.host | quote }}
  db.port: {{ .Values.monolith.db.port | quote }}
  db.username: {{ .Values.monolith.db.username | quote }}
  db.password: {{ .Values.monolith.db.password | quote }}
  db.database: {{ .Values.monolith.db.database | quote }}