apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fastfood.fullname" . }}-order-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fastfood.fullname" . }}-order
  minReplicas: {{ .Values.order.hpa.minReplicas }}
  maxReplicas: {{ .Values.order.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.order.hpa.cpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.order.hpa.memoryAverageUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.order.hpa.stabilizationWindowSeconds }}