apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastfood.fullname" . }}-order-service
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
spec:
  type: {{ .Values.order.service.type }}
  selector:
    app.kubernetes.io/component: order
  {{- include "fastfood.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.order.service.protocol }}
      port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.port }}