apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastfood.fullname" . }}-order-config
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
data:
  app.host: {{ .Values.order.host | quote }}
  app.port: {{ .Values.order.port | quote }}
  app.jwt_secret: {{ .Values.order.jwt.secret | quote }}
  db.type: mysql
  db.host: {{ .Values.order.db.host | quote }}
  db.port: {{ .Values.order.db.port | quote }}
  db.username: {{ .Values.order.db.username | quote }}
  db.password: {{ .Values.order.db.password | quote }}
  db.database: {{ .Values.order.db.database | quote }}